### ISSUE TITLE
User Guide

### ISSUE THREAD

**Issue by MadibaJ** [kmahon37/plex-dvr-waker#17]
This is a me issue, but could be clarified in the instructions. I'm in construction so my IT is limited. 

I've installed Net 2.2.8 and restarted my machine. 
I've extracted the PlexDvrWaker files into D:\PlexDvrWaker
I then open a command prompt in Adminstrator
I then get the error message as per the snip attached. 

![image](https://user-images.githubusercontent.com/63946263/79681498-0e7f9380-825e-11ea-8ea5-545b084df31f.png)

**Comment by MadibaJ** [comment]
OK fixed....I had installed the wrong .net also running from D;\ didnt work but worked when moved to c;|

**Comment by kmahon37** [comment]
FYI... If you downloaded v1.1.7 in the last couple days, you will want to download and install [v1.1.6](https://github.com/kmahon37/plex-dvr-waker/releases/tag/v1.1.6) instead because v1.1.7 is not working properly (I actually just deleted v1.1.7 this morning).  After installing v1.1.6, make sure to rerun any `add-task` commands you may have run previously so that the Task Scheduler tasks will get recreated properly.
