### ISSUE TITLE
[BUG] 'No upcoming scheduled recordings' when using xmltv based EPG

### ISSUE THREAD

**Issue by thrnz** [kmahon37/plex-dvr-waker#8]
**Describe the bug**
plex-dvr-waker reports 'no upcomming scheduled recordings' when Plex gets its listings from an xmltv file.

**To Reproduce**
- When setting up a DVR in Plex, choose to get EPG data from an xmltv file. 
- Create some scheduled recordings.
- Run a 'list' - no recordings will be found.

**Expected behavior**
plex-dvr-waker to function the same as when using a Plex supplied EPG.

**Desktop (please complete the following information):**
 - Plex DVR Waker version: 1.1.2
 - Windows version: Windows 10 Pro 1903
 - .NET Core version: 2.2.8 x86

**Additional context**
It looks like plex-dvr-waker searches for 'tv.plex.providers.epg.cloud*.db' when looking for the EPG database. However, when using an xmltv based EPG, Plex appears to use a 'tv.plex.providers.epg.xmltv*.db' filename instead.

I've managed to work around it by making appropriately named symlinks (simply replacing xmltv with cloud) of the .db .db-shm, and .db-wal files so plex-dvr-waker can still work. I'm not sure if this workaround will effect 'monitor' or not, or whether the xmltv db might have a slightly different structure ('list' doesn't appear to be showing the schedule titles, however start/finish times are listed correctly), however 'sync' appears to be working fine and creating the wake-up task as expected.

I can provide a copy of some xmltv db files if you want to have a poke around.

Thanks for taking the time to make this btw. It does one job and does it well.

**Comment by kmahon37** [comment]
@thrnz You are correct that Plex DVR Waker only looks at the "cloud" file(s), but only because I didn't know anything else existed.  If you can provide a copy of an "xmltv" db file, that may help (I'm hoping it's the same format as the "cloud" file).  I might also have to try setting up my DVR with an xmltv file when I get some time.

**Comment by thrnz** [comment]
Here's a copy of my epg db files. Hopefully there's nothing account sensitive in there: [xmltvdb.zip](https://github.com/kmahon37/plex-dvr-waker/files/4173638/xmltvdb.zip)

**Comment by kmahon37** [comment]
Thanks for the file.  As far as I know, and after a quick glance, I don't think there is anything sensitive in it (mostly just show metadata like names, descriptions, times, channel, etc.).  The database structure appears to be the same as the "cloud" file, so that should hopefully make it easier to fix.

**Comment by kmahon37** [comment]
@thrnz I think I may have fixed it, but it's hard to tell for sure since I can't get my Plex to use xmltv for some reason (maybe because I already have a dvr setup?).  Can you test out [this prerelease version](https://github.com/kmahon37/plex-dvr-waker/files/4174654/PlexDvrWaker.1.1.3.zip) and see if it works for you without the symlinks?

**Comment by thrnz** [comment]
I had a quick play and it seems to be working fine without the symlinks. I'll keep a close eye on it over the next week or so and will let you know if I see anything strange.

Nice work.

**Comment by kmahon37** [comment]
Fixed in 1.1.3
